# Generated by Django 2.1.3 on 2018-11-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181128_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.BooleanField(null=True),
        ),
    ]
