# Generated by Django 2.1.3 on 2018-12-02 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
    ]
