# Generated by Django 2.0 on 2018-11-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181128_2254'),
        ('posts', '0005_auto_20181129_0038'),
    ]

    operations = [
    ]
